
development:
  adapter: mysql
  encoding: utf8
  database: mytwu
  # host: instance3058.db.xeround.com:3404
  host: ec2-50-19-122-8.compute-1.amazonaws.com
  port: 3404
  # pool: 5
  username: phwuxj
  password: wuzhu99

test:
  adapter: mysql
  encoding: utf8
  database: mytwu
  # host: instance3058.db.xeround.com:3404
  host: ec2-50-19-122-8.compute-1.amazonaws.com
  port: 3404
  # pool: 5
  username: phwuxj
  password: wuzhu99

production:
  adapter: mysql
  encoding: utf8
  database: mytwu
  # host: instance3058.db.xeround.com:3404
  host: ec2-50-19-122-8.compute-1.amazonaws.com
  port: 3404
  # pool: 5
  username: phwuxj
  password: wuzhu99

